tag @s add disguised
playsound random.orb @s
tag @s remove bat
tag @s remove blaze
tag @s remove slime
tag @s remove cow
tag @s remove husk
tag @s remove minecart
tag @s remove creeper
tag @s remove ghast
tag @s remove iron_golem
tag @s remove enderman
tag @s remove zombie
tag @s remove wither_skeleton
tag @s remove arrow
tag @s remove xp_orb
tag @s remove cod
tag @s remove cat
tag @s remove salmon
tag @s remove panda
tag @s remove sheep
tag @s remove pig
tag @s remove chicken
tag @s remove wolf
tag @s remove tnt
tag @s remove ocelot
tag @s remove polar_bear
tag @s remove mooshroom
tag @s remove parrot
tag @s remove rabbit
tag @s remove llama
tag @s remove horse
tag @s remove mule
tag @s remove donkey
tag @s remove zombie_horse
tag @s remove skeleton_horse
tag @s remove pufferfish
tag @s remove dolphin
tag @s remove turtle
tag @s remove silverfish
tag @s remove skeleton
tag @s remove stray
tag @s remove spider
tag @s remove cave_spider
tag @s remove squid
tag @s remove guardian
tag @s remove elder_guardian
tag @s remove drowned
tag @s remove zombie_pigman
tag @s remove witch
tag @s remove endermite
tag @s remove magma_cube
tag @s remove vindicator
tag @s remove evoker
tag @s remove vex
tag @s remove villager
tag @s remove ravager
tag @s remove shulker
tag @s remove pillager
tag @s remove phantom
tag @s remove zombie_villager
tag @s remove wandering_trader
tp @e[tag=disguise,r=2,c=1] ~ -10 ~